- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart shaker service
  ansible.builtin.systemd:
    name: "{{ simrig_service_name }}.service"
    state: restarted

- name: Reapply ALSA levels
  ansible.builtin.systemd:
    name: simrig-alsa.service
    state: restarted
