M48
; DRILL file KiCad 10.0.6 date 2026-09-30T10:28:50
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-30T10:28:50-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X27.5Y-49.5
X27.5Y-98.5
X85.5Y-49.5
X85.5Y-98.5
T2
X80.25Y-63.122
X80.25Y-74.552
X80.25Y-80.623
X80.25Y-92.052
M30
